export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const SET_INGREDIENT = 'SET_INGREDIENT'
export const FETCH_INGREDIENT_FAIL = 'FETCH_INGREDIENT_FAIL'

export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL'
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT'

export const FECTH_ORDERS_START = 'FECTH_ORDERS_START'
export const FECTH_ORDERS_SUCESS = 'FECTH_ORDERS_SUCESS'
export const FECTH_ORDERS_FAIL = 'FECTH_ORDERS_FAIL'

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCESS = 'AUTH_SUCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_ATUH_REDIRECT_PATH = 'SET_ATUH_REDIRECT_PATH'